#deadd-notification-center &
dunst &
xbindkeys &
#setxkbmap -option caps:none
setxkbmap gb
dbus-update-activation-environment --systemd DISPLAY
eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,gpg,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK
export QT_STYLE_OVERRIDE=kvantum
export QT_QPA_PLATFORMTHEME=qt5ct
sleep 1 && xrandr --output VGA1 --auto --left-of LVDS1 && feh --bg-fill /home/stephen/Pictures/Wallpapers/.wallpaper/* --bg-fill /home/stephen/Pictures/Wallpapers/.wallpaper/* &
exec i3
